-- Łysy Trener App — import atlasu ćwiczeń z pliku NEW FBW 2026.xlsx
-- Wklej całość w Supabase → SQL Editor → Run
create table if not exists exercises (
  id uuid default gen_random_uuid() primary key,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  slug text unique not null,
  name text not null,
  muscle_group text not null,
  equipment text,
  primary_muscles text,
  description text,
  video_url text,
  source_order integer
);

alter table exercises disable row level security;

create unique index if not exists exercises_slug_idx on exercises(slug);

insert into exercises (slug, name, muscle_group, equipment, primary_muscles, description, video_url, source_order)
values
('klatka-piersiowa-wyciskanie-sztangi-na-lawce-prostej', 'Wyciskanie sztangi na ławce prostej', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://youtube.com/shorts/sRuKSZLcmWM?si=UrHxy3SalV80QmUi', 1),
('klatka-piersiowa-wyciskanie-hantli-na-lawce-prostej', 'Wyciskanie hantli na ławce prostej', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/Gf65Yy0-wGI', 2),
('klatka-piersiowa-rozpietki-na-lawce-skosnej', 'Rozpiętki na ławce skośnej', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/4q-5NMYuwog', 3),
('klatka-piersiowa-pompki-klasyczne', 'Pompki klasyczne', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/4Bc1tPaYkOo', 4),
('klatka-piersiowa-pompki-na-poreczach', 'Pompki na poręczach', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/eicOUO9WaJc', 5),
('klatka-piersiowa-wyciskanie-sztangi-na-lawce-skosnej', 'Wyciskanie sztangi na ławce skośnej', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/98HWfiRonkE', 7),
('klatka-piersiowa-rozpietki-na-lawce-prostej', 'Rozpiętki na ławce prostej', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/rk8YayRoTRQ', 8),
('klatka-piersiowa-wyciskanie-hantli-na-lawce-skosnej', 'Wyciskanie hantli na ławce skośnej', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/ou6s32mJgjU', 9),
('klatka-piersiowa-butterfly-pec-deck', 'Butterfly (pec deck)', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/b3EzlAHSM3E', 10),
('klatka-piersiowa-krzyzowanie-linek-wyciagu', 'Krzyżowanie linek wyciągu', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://youtube.com/shorts/AJhU25QU7A0?si=qL8kEmFO3luv6o9w', 11),
('klatka-piersiowa-pompki-diamentowe', 'Pompki diamentowe', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/fFOH_RjxnHY', 13),
('klatka-piersiowa-squeeze-press', 'Squeeze press', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/Fk1lGJse0ho', 14),
('klatka-piersiowa-decline-chest-press-machine', 'Decline Chest Press Machine', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/0LPmZXwtzqQ', 15),
('klatka-piersiowa-incline-chest-press-machine', 'Incline Chest Press Machine', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=fGKgYWmVy7I&pp=ygUbSW5jbGluZSBDaGVzdCBQcmVzcyBNYWNoaW5l', 16),
('klatka-piersiowa-wide-chest-press-machine', 'Wide Chest Press Machine', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/GKRu_ap4x8o', 17),
('klatka-piersiowa-chest-press', 'Chest press', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/Qu7-ceCvq7w', 18),
('klatka-piersiowa-decline-bench-chest-press', 'Decline bench chest press', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/a-UFQE4oxWY', 20),
('klatka-piersiowa-smith-machine-press', 'Smith machine press', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/09SdlOtsllY', 23),
('klatka-piersiowa-landmine-press', 'Landmine press', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/wMSpAICXUb4', 24),
('klatka-piersiowa-incline-push-ups', 'Incline push-ups', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/CmaOCniUvfo', 25),
('klatka-piersiowa-push-ups-with-resistance-band', 'Push-ups with resistance band', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=cOFwFzzLFWw&pp=ygUdUHVzaC11cHMgd2l0aCByZXNpc3RhbmNlIGJhbmQ%3D', 26),
('klatka-piersiowa-single-arm-chest-press', 'Single arm chest press', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=d6Ba29xFBnw&pp=ygUWU2luZ2xlIGFybSBjaGVzdCBwcmVzcw%3D%3D', 29),
('klatka-piersiowa-medicine-ball-push-ups', 'Medicine ball push-ups', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=7GKXPkPKlI0&pp=ygUWTWVkaWNpbmUgYmFsbCBwdXNoLXVwcw%3D%3D', 31),
('klatka-piersiowa-wide-grip-push-ups', 'Wide grip push-ups', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/6VL_GzwnjFQ', 32),
('klatka-piersiowa-isometric-chest-squeeze', 'Isometric chest squeeze', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/0ZUws4lds7I', 33),
('klatka-piersiowa-resistance-band-flyes', 'Resistance band flyes', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/nvSvFqbe-xg', 34),
('klatka-piersiowa-incline-smith', 'Incline Smith', 'Klatka piersiowa', NULL, 'Klatka piersiowa', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/98HWfiRonkE', 35),
('plecy-martwy-ciag', 'Martwy ciąg', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/xNwpvDuZJ3k', 38),
('plecy-martwy-ciag-sumo', 'Martwy ciąg SUMO', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/e7oLkRlT2CQ', 39),
('plecy-wioslowanie-sztanga', 'Wiosłowanie sztangą', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/0Ty_MbK8uqU', 40),
('plecy-wioslowanie-sztanga-podchwytem', 'Wiosłowanie sztangą podchwytem', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/c-xJ_aYJseE', NULL),
('plecy-wioslowanie-hantlem', 'Wiosłowanie hantlem', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/yHqqGd0tXcw', 41),
('plecy-sciaganie-drazka-do-klatki', 'Ściąganie drążka do klatki', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/5s6KGLTMgoI', 42),
('plecy-sciaganie-drazka-do-karku', 'Ściąganie drążka do karku', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/oNqSkqsDNzw', 43),
('plecy-podciaganie-na-drazku', 'Podciąganie na drążku', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://youtube.com/shorts/eDP_OOhMTZ4?si=k0RS9oFEgXNxYU8Y', 44),
('plecy-lat-pulldown-machine', 'Lat pulldown machine', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/VsKaPtJfOkY', 45),
('plecy-wioslowanie-na-maszynie', 'Wiosłowanie na maszynie', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/-Nl_IfZge7U', 46),
('plecy-wioslowanie-na-maszynie-typu-hammer', 'Wiosłowanie na maszynie - typu HAMMER', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/Zpq1KQLFMLA', 47),
('plecy-wioslowanie-na-maszynie-seated-row', 'Wiosłowanie na maszynie - SEATED ROW', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/Kh2WA2Y1M0k', 48),
('plecy-face-pull', 'Face pull', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/IeOqdw9WI90', 49),
('plecy-martwy-ciag-na-prostych-nogach-rdl', 'Martwy ciąg na prostych nogach RDL', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/Rg27bvMeTKA', 50),
('plecy-shrugsy-z-hantlami', 'Shrugsy z hantlami', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/rFsSeClGnNA', 51),
('plecy-shrugsy-ze-sztanga', 'Shrugsy ze sztangą', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=NbmPVc19aJQ&pp=ygUTU2hydWdzeSB6ZSBzenRhbmfEhQ%3D%3D', 52),
('plecy-shrugsy-ze-sztanga-hex', 'Shrugsy ze sztangą HEX', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/VolLWhGZp4g', 53),
('plecy-wioslowanie-lina-na-wyciagu', 'Wiosłowanie liną na wyciągu', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/Rlrb3HU11w4', 54),
('plecy-wioslowanie-lina-na-wyciagu-szeroko-tbar', 'Wiosłowanie liną na wyciągu SZEROKO (TBAR)', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/vqPY3fDessY', 55),
('plecy-wioslowanie-lina-na-wyciagu-wasko-vbar', 'Wiosłowanie liną na wyciągu Wąsko (VBAR)', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/qD1WZ5pSuvk', 56),
('plecy-pullover', 'Pullover', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/1tWmRBJwzsY', 57),
('plecy-podciaganie-nachwytem', 'Podciąganie nachwytem', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/FsPu2AC84Og', 59),
('plecy-podciaganie-podchwytem', 'Podciąganie podchwytem', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/9D-HDSHOsoc', 60),
('plecy-hammer-strength-row', 'Hammer strength row', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/VHXOmrs56GU', 61),
('plecy-landmine-row', 'Landmine row', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/Sr2q7i-i8X0', 62),
('plecy-seal-row', 'Seal row', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/7pJGYosaTUQ', 63),
('plecy-t-bar-row', 'T-bar row', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/LqcrXVrNqPc', 64),
('plecy-reverse-flyes', 'Reverse flyes', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=bMD474hAjDE&pp=ygUNUmV2ZXJzZSBmbHllcw%3D%3D', 65),
('plecy-straight-arm-pulldown', 'Straight arm pulldown', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/hAMcfubonDc', 66),
('plecy-cable-row', 'Cable row', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/LyZH4UGdDTc', 67),
('plecy-unilateral-cable-row', 'Unilateral cable row', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/yIvvQc2Z6uM', 68),
('plecy-good-mornings', 'Good mornings', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/BegWt23YlLE', 69),
('plecy-superman', 'Superman', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/3HPU-jkUpHQ', 70),
('plecy-kettlebell-swing', 'Kettlebell swing', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/WgURqk-IPMg', 71),
('plecy-inverted-row', 'Inverted row', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=KOaCM1HMwU0&pp=ygUMSW52ZXJ0ZWQgcm93', 72),
('plecy-one-arm-lat-pulldown', 'One-arm lat pulldown', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/8zA8DjHRaq0', 73),
('plecy-resistance-band-row', 'Resistance band row', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/bBpK36TAQww', 74),
('plecy-deadstop-row', 'Deadstop row', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=1xO7aN5judg&pp=ygUMRGVhZHN0b3Agcm93', 75),
('plecy-chin-up-hold', 'Chin-up hold', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/bxguzp1DCFw', 76),
('plecy-gorilla-front-squat-over-head-press-military', 'Gorilla front squat + Over head press(Military)', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/MPDZqGSmcI8', 78),
('plecy-gorilla-row', 'Gorilla Row', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/e9oCtQdOwU4', 79),
('plecy-rdl-z-hantlami', 'RDL z HANTLAMI', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/CBOhr6H7BEY', 80),
('plecy-incline-dumbell-row', 'Incline Dumbell Row', 'Plecy', NULL, 'Plecy', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/4v59ShSjX2w', 81),
('barki-wyciskanie-hantli-nad-glowe', 'Wyciskanie hantli nad głowę', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/7sFktJVMBnA', 83),
('barki-arnoldki', 'Arnoldki', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=FVMC9qEbnrE&pp=ygUIQXJub2xka2k%3D', 84),
('barki-unoszenie-bokiem-hantlami', 'Unoszenie bokiem(Hantlami)', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/Kl3LEzQ5Zqs', 85),
('barki-unoszenie-w-opadzie', 'Unoszenie w opadzie', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/LsT-bR_zxLo', 86),
('barki-unoszenie-bokiem-jednoracz-na-wd', 'Unoszenie Bokiem jednorącz na WD', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/KVauca12MF4', 87),
('barki-unoszenie-ramion-do-tylu-w-opadzie-wd', 'Unoszenie Ramion do tyłu w opadzie WD', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=2OMbdPF7mz4&pp=ygURY3Jvc3MgY2FibGUgcmFpc2U%3D', 88),
('barki-wyciskanie-sztangi-zza-karku', 'Wyciskanie sztangi zza karku', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=BrSUvcuA49Y&pp=ygUcV3ljaXNrYW5pZSBzenRhbmdpIHp6YSBrYXJrdQ%3D%3D', 90),
('barki-unoszenie-hantli-w-przod', 'Unoszenie hantli w przód', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/9ThlTL25DH8', 92),
('barki-ohp', 'OHP', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/4LBVP2Oe7fg', 93),
('barki-lateral-raise-machine', 'Lateral raise machine', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/-t0pCJDUXHs', 94),
('barki-wyciskanie-hantli-siedzac-ohp', 'Wyciskanie Hantli siedząc OHP', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/k6tzKisR3NY', 95),
('barki-unoszenie-talerza', 'Unoszenie talerza', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=-NmE4t_Wkng&pp=ygURVW5vc3plbmllIHRhbGVyemE%3D', 96),
('barki-wznosy-hantli-w-opadzie', 'Wznosy hantli w opadzie', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=Ymd0mbBF8U4&pp=ygUXV3pub3N5IGhhbnRsaSB3IG9wYWR6aWU%3D', 97),
('barki-rear-delt-fly', 'Rear delt fly', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/AChrml938t8', 98),
('barki-cuban-press', 'Cuban press', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=XpcOM9Np9LQ&pp=ygULQ3ViYW4gcHJlc3M%3D', 100),
('barki-landmine-shoulder-press', 'Landmine shoulder press', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=QDzROn40xz8&pp=ygUXTGFuZG1pbmUgc2hvdWxkZXIgcHJlc3M%3D', 101),
('barki-cable-lateral-raise', 'Cable lateral raise', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/9ilIKuy6B0g', 102),
('barki-reverse-pec-deck', 'Reverse pec deck', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/7tgx6QHB0-A', 103),
('barki-front-raise-z-lina', 'Front raise z liną', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/v2ESoWx17tk', 105),
('barki-shoulder-press-machine', 'Shoulder press machine', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/6v4nrRVySj0', 106),
('barki-z-press', 'Z-press', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/FUJPvAD9jOo', 107),
('barki-wall-slides', 'Wall slides', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=oMSVe7PWJ3o&pp=ygULV2FsbCBzbGlkZXM%3D', 110),
('barki-isometric-lateral-hold', 'Isometric lateral hold', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=bH55OgdRn0c&pp=ygUWSXNvbWV0cmljIGxhdGVyYWwgaG9sZNIHCQlPCgGHKiGM7w%3D%3D', 111),
('barki-dumbbell-i-y-t-raises', 'Dumbbell I-Y-T raises', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/p6qJlRFmiNA', 112),
('barki-face-pull-z-rotacja', 'Face pull z rotacją', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=51AuMQzpBVY&pp=ygUXZmFjZSBwdWxsIHdpdGggcm90YXRpb24%3D', 113),
('barki-resistance-band-press', 'Resistance band press', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/79wEenoO-EY', 114),
('barki-half-kneeling-press', 'Half-kneeling press', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=-7zgcCU2kW4&pp=ygUTSGFsZi1rbmVlbGluZyBwcmVzcw%3D%3D', 115),
('barki-single-arm-ohp', 'Single arm OHP', 'Barki', NULL, 'Barki', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/S1Kf4Xi8pxo', 116),
('nogi-przysiady-ze-sztanga', 'Przysiady ze sztangą', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/dW3zj79xfrc', 118),
('nogi-wykroki', 'Wykroki', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/1mHlkUC5rGY', 119),
('nogi-przysiady-bulgarskie', 'Przysiady bułgarskie', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/or1frhkjBDc', 121),
('nogi-hip-thrust', 'Hip thrust', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/96uDbymTaHM', 122),
('nogi-wypychanie-na-suwnicy-leg-press-matrix', 'Wypychanie na suwnicy - LEG PRESS (MATRIX)', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/nP7FJZOiuS4', 123),
('nogi-wypychanie-na-suwnicy-leg-press-hammer', 'Wypychanie na suwnicy - LEG PRESS (HAMMER)', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/EotSw18oR9w', 124),
('nogi-goblet-squat', 'Goblet SQUAT', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/cuUPtfanAFQ', 125),
('nogi-przywodzenie-nog-hip-adduction', 'Przywodzenie nóg (Hip Adduction)', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/BmMmt-c9aNM', 126),
('nogi-odwodzenie-nog-hip-abduction', 'Odwodzenie nóg (Hip Abduction)', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/tu4o4quPv2k', 127),
('nogi-zginanie-nog-na-maszynie', 'Zginanie nóg na maszynie', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/_lgE0gPvbik', 128),
('nogi-prostowanie-nog-na-maszynie', 'Prostowanie nóg na maszynie', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/iQ92TuvBqRo', 129),
('nogi-sumo-przysiady', 'Sumo przysiady', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/cuUPtfanAFQ', 130),
('nogi-zakroki', 'Zakroki', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/YZHLuFib8JU', 131),
('nogi-wchodzenie-na-skrzynie', 'Wchodzenie na skrzynię', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=PxJ_o89IMJA&pp=ygUXV2Nob2R6ZW5pZSBuYSBza3J6eW5pxJk%3D', 133),
('nogi-zurawie-nordyckie', 'Żurawie nordyckie', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/WHkAU7fRVFc', 134),
('nogi-spacer-farmera', 'Spacer farmera', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=T02vU6MdLik&pp=ygUOU3BhY2VyIGZhcm1lcmE%3D', 135),
('nogi-wspiecia-na-palce', 'Wspięcia na palce', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/cvpQWqxYsjc', 136),
('nogi-przysiady-z-pauza', 'Przysiady z pauzą', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/mGZN7_T0trA', 137),
('nogi-jump-squat', 'Jump squat', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=BRfxI2Es2lE&pp=ygUKSnVtcCBzcXVhdA%3D%3D', 138),
('nogi-wall-sit', 'Wall sit', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=SszDMOZvFuw&pp=ygUIV2FsbCBzaXQ%3D', 139),
('nogi-hack-squat', 'Hack squat', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/bGbHOeHXnB8', 140),
('nogi-incline-squat', 'INCLINE squat', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/NxCntzwABlY', 141),
('nogi-single-leg-press', 'Single leg press', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/LbKwZIbVYZI', 142),
('nogi-curtsy-lunge', 'Curtsy lunge', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/-i1G2YuuDW0', 143),
('nogi-deadlift-trap-bar', 'Deadlift trap bar', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=EsqwERaSTMI&pp=ygURRGVhZGxpZnQgdHJhcCBiYXI%3D', 144),
('nogi-jump-lunge', 'Jump lunge', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=iJMsF7fzrOM&pp=ygUKSnVtcCBsdW5nZQ%3D%3D', 145),
('nogi-step-up', 'Step up', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/wEnxQmNwans', 146),
('nogi-sled-push', 'Sled push', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/w0OH_C6166M', 147),
('nogi-heel-elevated-squat', 'Heel elevated squat', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/UPeQpDPRWOg', 148),
('nogi-kick-back', 'KICK back', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/sllbiOqpUso', 149),
('nogi-rear-leg-rise-donkey-kick', 'REAR LEG Rise (Donkey Kick)', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/watch?v=EtSJ8rwm5M8&pp=ygUbUkVBUiBMRUcgUmlzZSAoRG9ua2V5IEtpY2sp', 150),
('nogi-walking-lunge', 'Walking lunge', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/2ea3_b9rFdM', 151),
('nogi-box-squat', 'Box squat', 'Nogi', NULL, 'Nogi', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', 'https://www.youtube.com/shorts/6_xQf5A3WmE', 152),
('biceps-uginanie-ramion-ze-sztanga', 'Uginanie ramion ze sztangą', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 154),
('biceps-uginanie-ramion-z-hantlami', 'Uginanie ramion z hantlami', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 155),
('biceps-uginanie-ramion-na-modlitewniku-preacher', 'Uginanie ramion na modlitewniku (PREACHER)', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 156),
('biceps-uginanie-mlotkowe-hammer-curl', 'Uginanie młotkowe - HAMMER CURL', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 157),
('biceps-uginanie-ramion-z-lina-wg-oburacz', 'Uginanie ramion z liną WG oburącz', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 158),
('biceps-uginanie-ramion-z-lina', 'Uginanie ramion z liną', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 159),
('biceps-uginanie-na-wd-lina', 'Uginanie na WD liną', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 160),
('biceps-uginanie-na-wd-drazkiem-prostym', 'Uginanie na WD drążkiem prostym', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 161),
('biceps-uginanie-na-wd-drazkiem-ez', 'Uginanie na WD drążkiem EZ', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 162),
('biceps-uginanie-koncentratyczne', 'Uginanie koncentratyczne', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 163),
('biceps-zottman-curl', 'Zottman curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 164),
('biceps-21s', '21s', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 165),
('biceps-uginanie-hantli-siedzac', 'Uginanie hantli siedząc', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 166),
('biceps-drag-curl', 'Drag curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 167),
('biceps-uginanie-jednoracz', 'Uginanie jednorącz', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 168),
('biceps-incline-dumbbell-curl-sit-up', 'Incline dumbbell curl (sit up)', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 169),
('biceps-cable-curl', 'Cable curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 170),
('biceps-barbell-preacher-curl', 'Barbell preacher curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 171),
('biceps-spider-curl', 'Spider curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 172),
('biceps-cross-body-curl', 'Cross body curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 173),
('biceps-reverse-curl', 'Reverse curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 174),
('biceps-banded-curl', 'Banded curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 175),
('biceps-rope-hammer-curl', 'Rope hammer curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 176),
('biceps-machine-curl', 'Machine curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 177),
('biceps-dumbbell-squeeze-curl', 'Dumbbell squeeze curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 178),
('biceps-slow-eccentric-curl', 'Slow eccentric curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 179),
('biceps-wide-grip-curl', 'Wide grip curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 180),
('biceps-close-grip-curl', 'Close grip curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 181),
('biceps-ez-bar-curl', 'EZ-bar curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 182),
('biceps-kettlebell-curl', 'Kettlebell curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 183),
('biceps-supinated-curl', 'Supinated curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 184),
('biceps-incline-cable-curl', 'Incline cable curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 185),
('biceps-overhead-cable-curl', 'Overhead cable curl', 'Biceps', NULL, 'Biceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 186),
('triceps-wyciskanie-francuskie', 'Wyciskanie francuskie', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 188),
('triceps-prostowanie-ramion-na-wg', 'Prostowanie ramion na WG', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 189),
('triceps-dipsy', 'Dipsy', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 190),
('triceps-wyciskanie-wasko', 'Wyciskanie wąsko', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 191),
('triceps-prostowanie-ramienia-w-opadzie', 'Prostowanie ramienia w opadzie', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 192),
('triceps-kickback', 'Kickback', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 193),
('triceps-prostowanie-z-linka-nad-glowa-na-wg', 'Prostowanie z linką nad głową na WG', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 194),
('triceps-prostowanie-z-drazka-prostego-na-wg', 'Prostowanie z drążka prostego na WG', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 195),
('triceps-prostowanie-tribar-na-wg', 'Prostowanie TriBar na WG', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 196),
('triceps-prostowanie-z-linka-wg', 'Prostowanie z linką  WG', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 197),
('triceps-skullcrusher', 'Skullcrusher', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 198),
('triceps-triceps-pushdown', 'Triceps pushdown', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 199),
('triceps-jednoracz-na-wyciagu', 'Jednorącz na wyciągu', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 200),
('triceps-triceps-overhead-extension', 'Triceps overhead extension', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 201),
('triceps-close-grip-bench-press', 'Close grip bench press', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 202),
('triceps-diamond-push-ups', 'Diamond push-ups', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 203),
('triceps-reverse-grip-pushdown', 'Reverse grip pushdown', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 204),
('triceps-cable-overhead-extension', 'Cable overhead extension', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 205),
('triceps-dumbbell-overhead-extension', 'Dumbbell overhead extension', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 206),
('triceps-incline-skullcrusher', 'Incline skullcrusher', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 207),
('triceps-lying-bar-extension', 'Lying bar extension', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 208),
('triceps-machine-dips', 'Machine dips', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 209),
('triceps-bench-dips', 'Bench dips', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 210),
('triceps-kettlebell-triceps-extension', 'Kettlebell triceps extension', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 211),
('triceps-cross-cable-extension', 'Cross cable extension', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 212),
('triceps-resistance-band-pushdown', 'Resistance band pushdown', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 213),
('triceps-isometric-triceps-hold', 'Isometric triceps hold', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 214),
('triceps-bodyweight-triceps-extension', 'Bodyweight triceps extension', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 215),
('triceps-barbell-jm-press', 'Barbell JM press', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 216),
('triceps-floor-press', 'Floor press', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 217),
('triceps-z-bar-skullcrusher', 'Z-bar skullcrusher', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 218),
('triceps-incline-dumbbell-kickback', 'Incline dumbbell kickback', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 219),
('triceps-straight-bar-pushdown', 'Straight bar pushdown', 'Triceps', NULL, 'Triceps', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 220),
('brzuch-plank', 'Plank', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 222),
('brzuch-crunch-plate-crunch', 'Crunch(plate Crunch)', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 223),
('brzuch-russian-twist', 'Russian twist', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 224),
('brzuch-leg-rise', 'Leg rise', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 225),
('brzuch-hanging-leg-rise', 'Hanging leg rise', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 226),
('brzuch-mountain-climber', 'Mountain climber', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 227),
('brzuch-bicycle-crunch', 'Bicycle crunch', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 228),
('brzuch-v-up', 'V-up', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 229),
('brzuch-reverse-crunch', 'Reverse crunch', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 230),
('brzuch-toes-to-bar', 'Toes to bar', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 231),
('brzuch-ab-wheel-rollout', 'Ab wheel rollout', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 232),
('brzuch-cable-crunch', 'Cable crunch', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 233),
('brzuch-sit-up', 'Sit-up', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 234),
('brzuch-plank-z-uniesieniem-nogi', 'Plank z uniesieniem nogi', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 235),
('brzuch-dead-bug', 'Dead bug', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 236),
('brzuch-dead-bug-z-obciazeniem', 'Dead bug z obciążeniem', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 237),
('brzuch-scissor-kicks', 'Scissor kicks', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 238),
('brzuch-side-plank', 'Side plank', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 239),
('brzuch-oblique-crunch', 'Oblique crunch', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 240),
('brzuch-woodchopper', 'Woodchopper', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 241),
('brzuch-side-bends', 'Side bends', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 242),
('brzuch-knee-tuck', 'Knee tuck', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 243),
('brzuch-dragon-flag', 'Dragon flag', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 244),
('brzuch-stir-the-pot', 'Stir the pot', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 245),
('brzuch-bear-crawl', 'Bear crawl', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 246),
('brzuch-cable-side-bend', 'Cable side bend', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 247),
('brzuch-medicine-ball-slam', 'Medicine ball slam', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 248),
('brzuch-jackknife-sit-up', 'Jackknife sit-up', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 249),
('brzuch-side-plank-raise', 'Side plank raise', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 250),
('brzuch-lying-windshield-wiper', 'Lying windshield wiper', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 251),
('brzuch-crunch-z-linka', 'Crunch z linką', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 252),
('brzuch-ball-crunch-z-obciazeniem', 'Ball Crunch z obciążeniem', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 253),
('brzuch-ball-crunch', 'Ball Crunch', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 254),
('brzuch-ball-pass-legs-to-hands', 'Ball pass (legs to hands)', 'Brzuch', NULL, 'Brzuch', 'Ćwiczenie z Twojego atlasu. Obejrzyj film i wykonuj ruch kontrolowanie, z zachowaniem techniki.', NULL, 255)
on conflict (slug) do update set
  name = excluded.name,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  primary_muscles = excluded.primary_muscles,
  description = excluded.description,
  video_url = excluded.video_url,
  source_order = excluded.source_order;